version: '3.5'

networks:
  localdev:
    name: localdev
    
services:
  main-api:
    build: TweetBook/
    restart: always
    ports:
      - "7000:80"
    #depends_on: 
      #- db-server
    networks:
      - localdev